### ISSUE TITLE
Increase draggable area of window borders

### ISSUE THREAD

**Issue by ishovkun** [andreyorst/Breezemite#2] opened 2017-02-10 05:54 UTC
The area to resize the window with the mouse pointer is ridiculously small. I almost cannot resize the windows with my mouse. The main decoration theme Breeze has significantly larger area for the mouse pointer to resize windows. Please, fix this.

**Comment by andreyorst** [comment] 2017-02-10 10:39
@ishovkun it's by design, see https://www.youtube.com/watch?v=4MycEcQOSzc
Just kidding, will be fixed soon.

**Comment by andreyorst** [comment] 2017-02-10 22:50
@ishovkun seems impossible to do, due the fact, that aurorae framework handles border sizes inside theme, and breeze isn't aurorae theme and borders are handled through kwin. Maybe i missing something.

I have 2 main variables to handle borders. It is "Border" and "Padding" for each side of a window. So for example i have borderless window with border = 0 and padding = 10, and if i want make this borderless window resizable with mouse, i need to set border to 3 and padding to 10 - 3 = 7. So i will have "invisible" borders which i can manipulate with mouse. But window size will change because padding was changed and borders were added, but borders are invisible, so now we have some kind of invisible frame around our "borderless" window. Why to hesitate if it invisible? Blur makes it visible. I've checked plenty of aurorae themes, same thing there.
![image](https://cloud.githubusercontent.com/assets/19470159/22847178/62106972-effc-11e6-8e03-f878edb0c1d9.png)

**Comment by ishovkun** [comment] 2017-02-11 03:46
I use a light theme LOL ;-)

**Comment by andreyorst** [comment] 2017-02-11 21:25
@ishovkun anyway i will leave this as it is, because i don't want to make theme ugly with this blur, or visible borders, because even now there is blur border by 1 pixel. And you still have possibility to resize window with alt + right mouse button combination.

If you want, you can adjust border and padding parameters in ~/.local/share/aurorae/themes/Breezemite/Breezemiterc
as i said before - increase border and decrease padding by equal number of pixels.

Sorry but i have no other possible way to help.

**Closed** 2017-02-13 09:17 UTC
Labels: enhancement, wontfix
